version: '2'
services:
  api:
    build: ./Server
    container_name: api
    depends_on:
      - mongo
    networks:
      - sub-etha
  mongo:
    image: mongo
    networks:
      - sub-etha
    ports:
      - '27017:27017'
  revproxy:
    build: './Reverse Proxy'
    depends_on:
      - api
      - ui
    networks:
      - sub-etha
    ports:
      - "80:80"
  ui:
    build: ./Client
    container_name: ui
    networks:
      - sub-etha
networks:
  sub-etha:
