version: '2'
services:
  api:
    build: ./API Service
    depends_on:
      - mongo
    networks:
      - sub-etha
  mongo:
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    image: mongo
    networks:
      - sub-etha
    ports:
      - 27017:27017
    volumes:
      - mongo_config_volume:/data/configdb
      - mongo_data_volume:/data/db
  ui:
    build: ./UI Service
    networks:
      - sub-etha
networks:
  sub-etha:
volumes:
  mongo_config_volume:
  mongo_data_volume:
